# Generated by Django 5.2.3 on 2025-06-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
