# Generated by Django 5.2.3 on 2025-06-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_delete_enrollment'),
        ('students', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
