# Generated by Django 5.2.3 on 2025-06-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
