# Generated by Django 5.2.3 on 2025-06-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
