# Generated by Django 5.2.3 on 2025-06-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
